input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["user-registered"]
    group_id => "logstash"
    auto_offset_reset => "earliest"
    codec => json
  }
}

filter {
  mutate {
    add_field => { "ingested_at" => "%{@timestamp}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "users-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
